# Generated by Django 2.2.24 on 2021-12-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='photo',
        ),
    ]
