# Generated by Django 2.2.24 on 2021-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_report_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.TextField(default='rua teste'),
            preserve_default=False,
        ),
    ]
