# Generated by Django 2.2.24 on 2021-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='district',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='street',
            field=models.TextField(max_length=100),
        ),
    ]
